<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-SBESDHB" failures="2" tests="5" name="Test" time="1459.464" errors="0" timestamp="2025-04-23T08:55:01 IST">
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="verify_account_registration" time="3.923"/>
  <testcase classname="testCases.TC002_LoginTest" name="verify_login" time="2.553"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="2.476"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="2.024">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDDT.verify_LoginDDT(TC003_LoginDDT.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_LoginDDT -->
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="10.15">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_LoginDDT.verify_LoginDDT(TC003_LoginDDT.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_LoginDDT -->
</testsuite> <!-- Test -->
